# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo.png"
    keywords: Z 左君国 Z的咖啡馆 zjg 左
    backgroundpic : "img/bg.png"

Intro:
    name: Kent Z
    slogan: "I am a slow walker, but I never walk backwards. <br/> Keep on keeping on!"
    HeadButton: Z's Café☕ #主页按钮上面的文字

Nav:
    Home_name: Home # 主页名字
    is_use_categories : true # 是否启用分类
    categories_name: Categorization   # 分类名字
    is_use_archives : false #是否启用归档
    archives_name: 归档 # 归档名字
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github:
            use: true # 是否启用
            link: https://github.com/zjgfree # 点击地址
        Twitter:
            use: false
            link:
        Facebook:
            use: false
            link:
        Instagram:
            use: false
            link:
        
    pages:
    # 自定义连接页
    # link 的参数为相对路径，对应 hexo 目录下的 source 件夹内的相应文件夹
        Resume: 
            link: "/resume/"
        Group :
            link: "/group/"
        Gallery :
            link: "/gallery/"
        Tag:
            link: "/tag/"
        About :
            link: "/about/"
        #自定义标签名
        #   link：“路径”

MainFirst:  # 导航栏下面的主页
    name: Kent Z # 大标题名字
    description: 欢迎来到我的小世界   # 第二标签 描述
    pic_url: /images/me.jpg # 图片地址
    goto_ulr: "" # 点击跳转

Gallery : # 图库页
    title:  
    description: 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
# false | duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views访问量系统
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML